//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public int idDoc { get; set; }
        public int documentType_idDocType { get; set; }
        public int setOfDocs_idSet { get; set; }
        public int nomenclature_idNom { get; set; }
        public Nullable<System.DateTime> dateDoc { get; set; }
        public Nullable<int> numberDoc { get; set; }
        public string filePath { get; set; }
        public Nullable<int> sheetsCount { get; set; }
    
        public virtual documentType documentType { get; set; }
        public virtual nomenclature nomenclature { get; set; }
        public virtual setOfDocs setOfDocs { get; set; }
    }
}
