//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_logbook
    {
        public int idEvent_logbook { get; set; }
        public int typeOfEvent_idTypeOfEvent { get; set; }
        public int organization_idOrg { get; set; }
        public System.DateTime dateOfEvent { get; set; }
        public string result { get; set; }
        public string responsibleOfEvent { get; set; }
        public Nullable<bool> done { get; set; }
    
        public virtual organization organization { get; set; }
        public virtual typeOfEvent typeOfEvent { get; set; }
    }
}
