//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizationArchive
    {
        public int idOrgArchive { get; set; }
        public Nullable<int> heating_idHeating { get; set; }
        public Nullable<int> shelving_idShelving { get; set; }
        public Nullable<int> cupboard_idCupboard { get; set; }
        public int organization_idOrg { get; set; }
        public Nullable<int> fundCount { get; set; }
        public Nullable<float> storageSquare { get; set; }
        public Nullable<float> filledCapacityPercent { get; set; }
        public Nullable<int> employeeCount { get; set; }
        public Nullable<float> timeOfStorage { get; set; }
        public string storageDescription { get; set; }
        public bool storageExistence { get; set; }
        public Nullable<bool> fireAlarm { get; set; }
        public Nullable<bool> securityAlarm { get; set; }
        public Nullable<bool> tempAndCoolConditions { get; set; }
        public string pathAboutArchive { get; set; }
        public string pathExpertCommission { get; set; }
        public string pathInstruction { get; set; }
    
        public virtual cupboard cupboard { get; set; }
        public virtual cupboard cupboard1 { get; set; }
        public virtual heating heating { get; set; }
        public virtual heating heating1 { get; set; }
        public virtual organization organization { get; set; }
        public virtual shelving shelving { get; set; }
        public virtual shelving shelving1 { get; set; }
    }
}
