//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public organization()
        {
            this.event_logbook = new HashSet<event_logbook>();
            this.nomenclature = new HashSet<nomenclature>();
            this.organizationArchive = new HashSet<organizationArchive>();
            this.renamesOfOrganization = new HashSet<renamesOfOrganization>();
            this.setOfDocs = new HashSet<setOfDocs>();
        }
    
        public int idOrg { get; set; }
        public int receivingForm_idRecForm { get; set; }
        public int collectionProfile_idColProf { get; set; }
        public int ownForm_idOwnForm { get; set; }
        public string nameOrg { get; set; }
        public Nullable<System.DateTime> foundationDate { get; set; }
        public string adress { get; set; }
        public string curator { get; set; }
        public string nameDirector { get; set; }
        public Nullable<long> phoneDirector { get; set; }
        public string emailDirector { get; set; }
        public string nameRespPers { get; set; }
        public Nullable<long> phoneRespPers { get; set; }
        public string emailRespPers { get; set; }
        public Nullable<bool> isSource { get; set; }
    
        public virtual collectionProfile collectionProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<event_logbook> event_logbook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nomenclature> nomenclature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizationArchive> organizationArchive { get; set; }
        public virtual ownForm ownForm { get; set; }
        public virtual receivingForm receivingForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<renamesOfOrganization> renamesOfOrganization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<setOfDocs> setOfDocs { get; set; }
    }
}
