//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class setOfDocs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public setOfDocs()
        {
            this.document = new HashSet<document>();
        }
    
        public int idSet { get; set; }
        public int organization_idOrg { get; set; }
        public int categoryOfSet_idCatOfSet { get; set; }
        public int access_idAccess { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> numberSet { get; set; }
        public Nullable<int> copies { get; set; }
        public string nameOfSet { get; set; }
        public string reasonOfClosedAccess { get; set; }
    
        public virtual access access { get; set; }
        public virtual categoryOfSet categoryOfSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document> document { get; set; }
        public virtual organization organization { get; set; }
    }
}
